//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MemoramaDB : DbContext
    {
        public MemoramaDB()
            : base("name=MemoramaDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Partida> Partida { get; set; }
        public virtual DbSet<Reporte> Reporte { get; set; }
        public virtual DbSet<SolicitudAmistad> SolicitudAmistad { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
