//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contratos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partida
    {
        public int IdPartida { get; set; }
        public string Nickname { get; set; }
        public Nullable<System.TimeSpan> Tiempo { get; set; }
        public Nullable<int> Difucultad { get; set; }
        public Nullable<int> Puntaje { get; set; }
        public string EstadoPartida { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
